#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_cocosbuilder_CCBAnimationManager_proto;
extern se::Class* __jsb_cocosbuilder_CCBAnimationManager_class;

bool js_register_cocosbuilder_CCBAnimationManager(se::Object* obj);
bool register_all_cocos2dx_builder(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_moveAnimationsFromNode);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setAutoPlaySequenceId);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getDocumentCallbackNames);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_actionForSoundChannel);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setBaseValue);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getDocumentOutletNodes);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getLastCompletedSequenceName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setRootNode);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_runAnimationsForSequenceNamedTweenDuration);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_addDocumentOutletName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getRootContainerSize);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setDocumentControllerName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setObject);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getContainerSize);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_actionForCallbackChannel);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getDocumentOutletNames);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_addDocumentCallbackControlEvents);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_init);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getKeyframeCallbacks);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getDocumentCallbackControlEvents);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setRootContainerSize);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_runAnimationsForSequenceIdTweenDuration);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getRunningSequenceName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getAutoPlaySequenceId);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_addDocumentCallbackName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getRootNode);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_addDocumentOutletNode);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setDelegate);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getSequenceDuration);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_addDocumentCallbackNode);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_runAnimationsForSequenceNamed);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getSequenceId);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setCallFunc);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getDocumentCallbackNodes);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_setSequences);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_debug);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_getDocumentControllerName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBAnimationManager_CCBAnimationManager);

extern se::Object* __jsb_cocosbuilder_CCBReader_proto;
extern se::Class* __jsb_cocosbuilder_CCBReader_class;

bool js_register_cocosbuilder_CCBReader(se::Object* obj);
bool register_all_cocos2dx_builder(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getAnimationManager);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_setAnimationManager);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_addOwnerOutletName);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getOwnerCallbackNames);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_addDocumentCallbackControlEvents);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_setCCBRootPath);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_addOwnerOutletNode);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getOwnerCallbackNodes);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_readSoundKeyframesForSeq);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getCCBRootPath);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getOwnerCallbackControlEvents);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getOwnerOutletNodes);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_readUTF8);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_addOwnerCallbackControlEvents);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getOwnerOutletNames);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_readCallbackKeyframesForSeq);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getAnimationManagersForNodes);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_getNodesWithAnimationManagers);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_setResolutionScale);
SE_DECLARE_FUNC(js_cocos2dx_builder_CCBReader_CCBReader);

