#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_cocos2d_ParticleSystem3D_proto;
extern se::Class* __jsb_cocos2d_ParticleSystem3D_class;

bool js_register_cocos2d_ParticleSystem3D(se::Object* obj);
bool register_all_cocos2dx_3d_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_resumeParticleSystem);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_startParticleSystem);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_isEnabled);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_getRender);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_isKeepLocal);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_setEnabled);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_getParticleQuota);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_getBlendFunc);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_pauseParticleSystem);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_getState);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_getAliveParticleCount);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_setParticleQuota);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_setBlendFunc);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_stopParticleSystem);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_setKeepLocal);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_ParticleSystem3D_ParticleSystem3D);

extern se::Object* __jsb_cocos2d_PUParticleSystem3D_proto;
extern se::Class* __jsb_cocos2d_PUParticleSystem3D_class;

bool js_register_cocos2d_PUParticleSystem3D(se::Object* obj);
bool register_all_cocos2dx_3d_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_initWithFilePath);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getParticleSystemScaleVelocity);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setEmittedSystemQuota);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getDefaultDepth);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getEmittedSystemQuota);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_initWithFilePathAndMaterialPath);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_clearAllParticles);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getMaterialName);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_calulateRotationOffset);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getMaxVelocity);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_forceUpdate);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getTimeElapsedSinceStart);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getEmittedEmitterQuota);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_isMarkedForEmission);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getDefaultWidth);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setEmittedEmitterQuota);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setMarkedForEmission);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_clone);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setDefaultWidth);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_copyAttributesTo);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setMaterialName);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getParentParticleSystem);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setMaxVelocity);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getDefaultHeight);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getDerivedPosition);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_rotationOffset);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getDerivedOrientation);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_removeAllEmitter);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setParticleSystemScaleVelocity);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_getDerivedScale);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setDefaultHeight);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_removeAllListener);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_initSystem);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_setDefaultDepth);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_create);
SE_DECLARE_FUNC(js_cocos2dx_3d_extension_PUParticleSystem3D_PUParticleSystem3D);

