language: cpp
script:
 - if [ $PLATFORM != android ]; then make -j4; fi
before_install:
 - if [ $PLATFORM = linux ]; then ./install-deps-linux.sh; fi
env:
 - PLATFORM=linux DEBUG=1
branches:
  only:
    - travis
