build:
  project: build\cocos2d-win32.vc2012.sln

branches:
  except:
    - /.*-osx/

configuration:
  - Release

platform:
  - x86
test: off  # disable automatic test discovery, xUnit already runs as part of build.cmd

