build:
  project: build\cocos2d-win32.vc2012.sln

install:
  - python download-deps.py -r=yes

branches:
  except:
    - /.*-osx/

configuration:
  - Release

#platf

test: off  # disable automatic test discovery, xUnit already runs as part of build.cmd

